VERSION --build-auto-skip 0.8

FROM alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

IMPORT ../../common AS common

ARG --global OS_IMAGE=ubuntu

ARG --global OS_VERSION=24.04
# renovate: datasource=github-releases depName=docker/docker
LET docker_package_version=28.5.2
ARG --global DOCKER_VERSION=5:$docker_package_version-1~ubuntu.$OS_VERSION~noble

# DIR_PATH is set to that common targets can call os specific targets. It should match the directory name this Earthfile is located in
ARG --global DIR_PATH=$OS_IMAGE-$OS_VERSION

# release builds the image using a new datetime as a suffix and run tests against the pushed image, then finally retag and push the image without the datetime suffix
release:
    RUN --no-cache date --utc +%Y%m%d%H%M%S > datetime
    LET datetime="$(cat datetime)"
    WAIT
        BUILD --pass-args common+build-and-test --SUFFIX=$datetime
    END
    COPY --dir --pass-args common+get-image-info/image-info .
    LET image_tag="$(cat image-info/tag)-$datetime"
    BUILD --pass-args common+push-new-tag-multi-platform --TAG_WITH_DATE=$image_tag

# test-build will build a test image that is pushed to a temporary registry and run tests against it
test-build:
    BUILD --pass-args common+build-and-test --IMAGE_NAME="dindtest"

# build builds an dind image
build:
    BUILD --pass-args --platform=linux/amd64 --platform=linux/arm64 common+build

# test runs test for a dind image
# this is primarly used to run against a newly, temporariy image build by +test-build
test:
    BUILD --pass-args common+ubuntu-kind-test
    BUILD --pass-args common+test
