name: Release

on:
  pull_request_target:
    types: [ closed ]

env:
  OTEL_SERVICE_NAME: ${{ vars.OTEL_SERVICE_NAME }}
  OTEL_EXPORTER_OTLP_ENDPOINT: ${{ vars.OTEL_EXPORTER_OTLP_ENDPOINT }}
  OTEL_EXPORTER_OTLP_PROTOCOL: ${{ vars.OTEL_EXPORTER_OTLP_PROTOCOL }}
  OTEL_RESOURCE_ATTRIBUTES: ${{ vars.OTEL_RESOURCE_ATTRIBUTES != '' && format('{0},', vars.OTEL_RESOURCE_ATTRIBUTES) || '' }}${{ github.event.pull_request != null && format('vcs.repository.change.id={0},vcs.repository.change.title={1},', github.event.pull_request.number, github.event.pull_request.title) || '' }}cicd.pipeline.run.id=${{ github.run_number }},cicd.pipeline.run.url.full=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }},cicd.pipeline.name=${{ github.workflow }},vcs.revision.id=${{ github.sha }},vcs.ref.name=${{ github.ref_name }},vcs.repository.name=${{ github.repository }},user.id=${{ github.actor }}
  OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}

jobs:
  release:
    name: release after merging ${{ github.head_ref }}
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'renovate/') && endsWith(github.head_ref, '-dind-image')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      EARTHLY_CONVERSION_PARALLELISM: "5"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      # The dind (common+alpine-kind-test and common+ubuntu-kind-test) detects
      # the host's IPv6 capability and then requires IPv6 NAT to create networks
      # for kind. So we load it here.
      # Ref: https://github.com/moby/moby/pull/47062
      - name: Load kernel module IPv6 NAT
        run: sudo modprobe ip6table_nat
      - name: Set up Docker Hub mirrors
        run: |
          sudo mkdir -p /etc/docker
          echo '{"registry-mirrors": ["https://mirror.gcr.io", "https://public.ecr.aws"]}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Set up QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo update-binfmts --display
      - uses: earthbuild/actions-setup@7203b7659050789bb533fb98edb5995384154306 # main

      - name: Log in to container registries (non fork only)
        run: |-
          docker login --username "${{ vars.DOCKERHUB_USERNAME }}" --password "${{ secrets.DOCKERHUB_TOKEN }}"
          docker login ghcr.io --username ${{ github.actor }} --password "${{ secrets.GITHUB_TOKEN }}"
        if: github.event.pull_request.head.repo.full_name == github.repository
      - name: Build & Push image
        run: |
          earth --ci -P --push +release --RENOVATE_BRANCH=${{github.head_ref}} # default:ghcr.io
          earth --ci -P --push +release --RENOVATE_BRANCH=${{github.head_ref}} --CR_HOST=docker.io
