name: Update Docker Hub READMEs

on:
  push:
    branches: [ main ]
    paths: [ docs/dockerhub.md ]

jobs:
  update-docker-hub-readmes:
    name: update dockerhub readmes
    runs-on: ubuntu-latest
    env:
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update DockerHub description for earthly/dind
        uses: peter-evans/dockerhub-description@v4.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: earthly/dind
          readme-filepath: ./docs/dockerhub.md
          short-description: Earthly dind (Docker In Docker) Images
