name: Update Docker Hub README

on:
  push:
    # branches: [ main ]
    # paths: [ README.md ]

jobs:
  update-docker-hub-readmes:
    name: update dockerhub readmes
    runs-on: ubuntu-latest
    env:
      # Used in our github action as the token - TODO: look to change it into an input
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Update DockerHub description for earthbuild/dind
        uses: peter-evans/dockerhub-description@v4.0.2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: earthbuild/dind
          short-description: The `dind` image is designed for EarthBuild targets that use the `WITH DOCKER` command
